language: php
php:
  - 5.6
  - 7.0

sudo: false

services:
  - docker

env:
  matrix:
    - RELEASE=stable COMPOSER_CHANNEL=stable
    - RELEASE=dev COMPOSER_CHANNEL=stable
    - RELEASE=stable COMPOSER_CHANNEL=snapshot

before_install:
  - echo 'sendmail_path = /bin/true' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - phpenv config-rm xdebug.ini
  - composer --verbose self-update --$COMPOSER_CHANNEL
  - composer --version
  - docker-compose -f docker-compose.yml.dist build
  - docker-compose -f docker-compose.yml.dist pull

install:
  - docker-compose -p commerce2 -f docker-compose.yml.dist up -d
  - composer --verbose install
  - phantomjs --webdriver=4444 &
  - mkdir web/sites/simpletest
  - ./bin/drush --root=$(pwd)/web si commerce_base --site-name="Commerce 2" --account-pass=admin --yes
  - ./scripts/install-demo.sh
  - curl -I http://localhost/

script:
  - cd $TRAVIS_BUILD_DIR
  - ./bin/phpunit --testsuite unit --group commerce
  - ./bin/phpunit --testsuite kernel --group commerce
  - ./bin/behat -f junit -f pretty -o std
